FROM python:3.10

WORKDIR /code 

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt 

COPY . .

EXPOSE 8000

# RUN python manage.py migrate
RUN python manage.py collectstatic --noinput 

# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "stocks_products.wsgi:application"]